local: false
markdown_ext: md
markdown: redcarpet
highlighter: rouge
url: http://aldrin.co
permalink: :title.html
timezone: America/New_York
defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
